### PR TITLE
Create Unit Profile - Buetify + Vee-validate proposal

### PR DESCRIPTION
**Pull request by pingwiniasty**
waiting for comments :D

### CODE REVIEW

**Comment by jarlah** [comment]
nice :D 🚀 Its a really nice css library, and seems to be miles easier than bootstrap. Therefore, lets use Buefy ;) 

I like how the validator is injected and how it automagically works inside the template. I also like that it can be easily tested 💯 

However, I suggest the following edit to App.vue template:

```
<template>
  <div id="app">
    <nav class="navbar is-white">
      <div class="navbar-brand">
        <a class="navbar-item brand-text">
          Freeacs
        </a>
        <div class="navbar-burger burger" data-target="navMenu">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>
      <div class="navbar-menu" id="navMenu">
        <div class="navbar-start">
          <router-link class="navbar-item" to="/">
            Home
          </router-link>
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link"><span><i class="mdi mdi-24px mdi-view-list"></i> Unit</span></a>
            <div class="navbar-dropdown is-hidden-touch">
              <router-link class="navbar-item" :to="{ name: 'unit-profile-create' }"><span><i class="mdi mdi-24px mdi-star"></i> Create Profile</span></router-link>
            </div>
          </div>
        </div>
        <div class="navbar-end">
          <router-link class="navbar-item" to="/about">
            About
          </router-link>
          <a class="navbar-item" v-if="isLoggedIn" @click="logout" href="#">
            Logout
          </a>
          <router-link class="navbar-item" v-else to="/login">
            Login
          </router-link>
        </div>
      </div>
    </nav>
    <div class="container">
      <router-view/>
    </div>
  </div>
</template>
```

which will produce the following layout

Screenshot 2019-04-18 at 10 07 06

Screenshot 2019-04-18 at 10 07 29

I wondered why there was so many `<div class="container">` inside the menu and removed them. And wrapped a container around the router-view instead. In addition to moving about and login/logout to navbar end.

**Comment by jarlah** [comment]
I now understand why you had containers in the menu, you wanted space from the left side, but I think its better to use all the possible real estate in the menu bar for menu items.

**Review by jarlah — CHANGES_REQUESTED** [review]
Good work :)
See comments on the pull request.

**Comment by pingwiniasty** [comment]
Changed App.vue from your proposal

**Review by jarlah — APPROVED** [review]
Nice. I think we will merge this now, and leave the original issue open for further development on integrating it with the backend, if you dont want to do it right now. We need the unittype list in state, so integration with backend requires more work.

**Comment by pingwiniasty** [comment]
Ok, I will merge it today, and do some work with api integration ;)

**Comment by jarlah** [comment]
oh and btw, the api backend uses h2 which is a bit flaky. you might have to restart it after a while.

**Pull request merged**
